# Form implementation generated from reading ui file 'D:\Pycharm_Files\MyPoeAssist\data\ui\item_helper.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 509)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_spy_clipboard = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_spy_clipboard.setObjectName("checkBox_spy_clipboard")
        self.horizontalLayout.addWidget(self.checkBox_spy_clipboard)
        self.checkBox_collect_mods = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_collect_mods.setObjectName("checkBox_collect_mods")
        self.horizontalLayout.addWidget(self.checkBox_collect_mods)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit_item_detail = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit_item_detail.setEnabled(True)
        self.plainTextEdit_item_detail.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.plainTextEdit_item_detail.setLineWidth(2)
        self.plainTextEdit_item_detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.plainTextEdit_item_detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_item_detail.setReadOnly(True)
        self.plainTextEdit_item_detail.setObjectName("plainTextEdit_item_detail")
        self.verticalLayout.addWidget(self.plainTextEdit_item_detail)
        self.textEdit_fenxi_result = QtWidgets.QTextEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fenxi_result.sizePolicy().hasHeightForWidth())
        self.textEdit_fenxi_result.setSizePolicy(sizePolicy)
        self.textEdit_fenxi_result.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textEdit_fenxi_result.setReadOnly(True)
        self.textEdit_fenxi_result.setObjectName("textEdit_fenxi_result")
        self.verticalLayout.addWidget(self.textEdit_fenxi_result)
        self.label_app_status = QtWidgets.QLabel(parent=Form)
        self.label_app_status.setObjectName("label_app_status")
        self.verticalLayout.addWidget(self.label_app_status)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_spy_clipboard.setText(_translate("Form", "监测剪贴板"))
        self.checkBox_collect_mods.setText(_translate("Form", "收集词缀"))
        self.label_app_status.setText(_translate("Form", "TextLabel"))
