# Form implementation generated from reading ui file 'D:\Pycharm_Files\MyPoeAssist\data\ui\mod_collect.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 637)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_load_conf = QtWidgets.QPushButton(parent=Form)
        self.pushButton_load_conf.setObjectName("pushButton_load_conf")
        self.horizontalLayout.addWidget(self.pushButton_load_conf)
        self.pushButton_save_conf = QtWidgets.QPushButton(parent=Form)
        self.pushButton_save_conf.setObjectName("pushButton_save_conf")
        self.horizontalLayout.addWidget(self.pushButton_save_conf)
        self.pushButton_print_new = QtWidgets.QPushButton(parent=Form)
        self.pushButton_print_new.setObjectName("pushButton_print_new")
        self.horizontalLayout.addWidget(self.pushButton_print_new)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit_all_mods = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit_all_mods.setReadOnly(True)
        self.plainTextEdit_all_mods.setObjectName("plainTextEdit_all_mods")
        self.verticalLayout.addWidget(self.plainTextEdit_all_mods)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_load_conf.setText(_translate("Form", "load conf"))
        self.pushButton_save_conf.setText(_translate("Form", "save conf"))
        self.pushButton_print_new.setText(_translate("Form", "print new"))
